kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bouncer
subjects:
- kind: ServiceAccount
  name: bouncer
roleRef:
  kind: Role
  name: bouncer
  apiGroup: rbac.authorization.k8s.io
