apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bouncer
  template:
    metadata:
      labels:
        name: bouncer
    spec:
      serviceAccountName: bouncer
      containers:
        - name: bouncer
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - bouncer
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bouncer"
